/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ActividadClase_17092021_Interfaz_BD_Menu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando F. Feijoo
 */
public class AgregarDatos extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form AgregarDatos
     */
    double sueldo;
    int edad;
    public AgregarDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txp_cedula = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txp_nombre = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txp_apellido = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txp_direccion = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txp_telefono = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txp_sueldo = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txp_edad = new javax.swing.JTextPane();
        btn_GuardarInformacion = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("AGREGAR DATOS DE USUARIO");

        jLabel2.setText("CEDULA");

        jLabel3.setText("NOMBRE");

        jLabel4.setText("APELLIDO");

        jLabel5.setText("DIRECCION");

        jLabel6.setText("TELEFONO");

        jLabel7.setText("SUELDO");

        jLabel8.setText("EDAD");

        jScrollPane1.setViewportView(txp_cedula);

        jScrollPane2.setViewportView(txp_nombre);

        jScrollPane3.setViewportView(txp_apellido);

        jScrollPane4.setViewportView(txp_direccion);

        jScrollPane5.setViewportView(txp_telefono);

        jScrollPane6.setViewportView(txp_sueldo);

        jScrollPane7.setViewportView(txp_edad);

        btn_GuardarInformacion.setText("GUARDAR INFORMACION");
        btn_GuardarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarInformacionActionPerformed(evt);
            }
        });

        btn_eliminar.setText("ELIMINAR DATOS");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_actualizar.setText("ACTUALIZAR DATOS");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_GuardarInformacion)
                        .addGap(18, 18, 18)
                        .addComponent(btn_actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_GuardarInformacion)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_eliminar))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarInformacionActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_btn_GuardarInformacionActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        actualizar();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_btn_eliminarActionPerformed
    
    public void guardar()
    { 
         sueldo = Double.parseDouble(txp_sueldo.getText());
         edad = Integer.parseInt(txp_edad.getText());
         try
         {
            Class.forName("org.postgresql.Driver");
            Connection conecta = DriverManager.getConnection("jdbc:postgresql://localhost:5432/FeijooBD_POO2","postgres","FerDatos95"); 
            
            Statement consulta=(Statement) conecta.createStatement();            
            consulta.executeUpdate("INSERT INTO public.datosclase(cedula, nombre, apellido, direccion, telefono, sueldo, edad) VALUES ('"+txp_cedula.getText()+"', '"+txp_nombre.getText()+"', '"+txp_apellido.getText()+"', '"+txp_direccion.getText()+"', '"+txp_telefono.getText()+"', '"+sueldo+"', '"+edad+"');");
          
            conecta.close();
            JOptionPane.showMessageDialog(null,"Registro guardado correctamente");

         } catch(SQLException e)
         {
            JOptionPane.showMessageDialog(null,"Error al guardar datos");

         } catch(ClassNotFoundException e)
         {
            JOptionPane.showMessageDialog(null,"Error inesperado");
    }
         txp_cedula.setText("");
         txp_nombre.setText("");
         txp_apellido.setText("");
         txp_direccion.setText("");
         txp_telefono.setText("");
         txp_sueldo.setText("");
         txp_edad.setText("");
    }
    
    public void actualizar()
    { 
         sueldo = Double.parseDouble(txp_sueldo.getText());
         edad = Integer.parseInt(txp_edad.getText());
         try
         {
            Class.forName("org.postgresql.Driver");
            Connection conecta = DriverManager.getConnection("jdbc:postgresql://localhost:5432/FeijooBD_POO2","postgres","FerDatos95"); 
            
            Statement consulta=(Statement) conecta.createStatement();            
            consulta.executeUpdate("UPDATE public.datosclase SET cedula = '"+txp_cedula.getText()+"', nombre = '"+txp_nombre.getText()+"', apellido = '"+txp_apellido.getText()+"', direccion = '"+txp_direccion.getText()+"', telefono = '"+txp_telefono.getText()+"', sueldo = '"+sueldo+"', edad = '"+edad+"' WHERE cedula = '"+txp_cedula.getText()+"';");
          
            conecta.close();
            JOptionPane.showMessageDialog(null,"Registro actualizado correctamente");

         } catch(SQLException e)
         {
            JOptionPane.showMessageDialog(null,"Error al actualizar datos");

         } catch(ClassNotFoundException e)
         {
            JOptionPane.showMessageDialog(null,"Error inesperado");
    }
         txp_cedula.setText("");
         txp_nombre.setText("");
         txp_apellido.setText("");
         txp_direccion.setText("");
         txp_telefono.setText("");
         txp_sueldo.setText("");
         txp_edad.setText("");
    }
    
    public void eliminar()
    { 
         try
         {
            Class.forName("org.postgresql.Driver");
            Connection conecta = DriverManager.getConnection("jdbc:postgresql://localhost:5432/FeijooBD_POO2","postgres","FerDatos95"); 
            
            Statement consulta=(Statement) conecta.createStatement();            
            consulta.executeUpdate("DELETE FROM public.datosclase WHERE cedula = '"+txp_cedula.getText()+"';");
          
            conecta.close();
            JOptionPane.showMessageDialog(null,"Registro eliminado correctamente");

         } catch(SQLException e)
         {
            JOptionPane.showMessageDialog(null,"Error al eliminar datos");

         } catch(ClassNotFoundException e)
         {
            JOptionPane.showMessageDialog(null,"Error inesperado");
    }
         txp_cedula.setText("");
         txp_nombre.setText("");
         txp_apellido.setText("");
         txp_direccion.setText("");
         txp_telefono.setText("");
         txp_sueldo.setText("");
         txp_edad.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GuardarInformacion;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane txp_apellido;
    private javax.swing.JTextPane txp_cedula;
    private javax.swing.JTextPane txp_direccion;
    private javax.swing.JTextPane txp_edad;
    private javax.swing.JTextPane txp_nombre;
    private javax.swing.JTextPane txp_sueldo;
    private javax.swing.JTextPane txp_telefono;
    // End of variables declaration//GEN-END:variables
}
