/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoo_feijoo;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANONYMOUS
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_listar = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txf_id = new javax.swing.JTextField();
        txf_area = new javax.swing.JTextField();
        txf_especie = new javax.swing.JTextField();
        txf_animalNombre = new javax.swing.JTextField();
        txf_habitad = new javax.swing.JTextField();
        txf_cuidador = new javax.swing.JTextField();
        txf_fecha = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_listar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORMULARIO ZOOLOGICO");

        tabla_listar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_listar);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txf_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txf_id.setToolTipText("");
        jPanel1.add(txf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 9, 160, -1));

        txf_area.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txf_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 45, 160, -1));

        txf_especie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txf_especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 129, 160, -1));

        txf_animalNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txf_animalNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 87, 160, -1));

        txf_habitad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txf_habitad, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 171, 160, -1));

        txf_cuidador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txf_cuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 213, 160, -1));

        txf_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txf_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 249, 160, -1));

        btn_buscar.setText("BUSCAR");
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });

        btn_guardar.setText("GUARDAR");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });

        btn_actualizar.setText("ACTUALIZAR");
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });

        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        btn_listar.setText("LISTAR");
        btn_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listarMouseClicked(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 22, 23, -1));

        jLabel3.setText("AREA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 56, -1, -1));

        jLabel4.setText("NOMBRE DE ANIMAL");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 96, -1, -1));

        jLabel5.setText("ESPECIE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 139, -1, -1));

        jLabel6.setText("HABITAD");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 181, -1, -1));

        jLabel7.setText("CUIDADOR");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 223, -1, -1));

        jLabel8.setText("FECHA");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 257, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(291, 291, 291)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)
                        .addComponent(btn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_listar))
                        .addGap(9, 9, 9)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:
        String id = txf_id.getText();
        String area = txf_area.getText();
        String animal = txf_animalNombre.getText();
        String especie = txf_especie.getText();
        String habitad = txf_habitad.getText();
        String cuidador = txf_cuidador.getText();
        String fecha = txf_fecha.getText();

        List<String> respuesta = guardar(id, area, animal, especie, habitad, cuidador, fecha);
        JOptionPane.showMessageDialog(null, respuesta.get(0));

        System.out.println(respuesta.get(1));
        if (respuesta.get(1).equalsIgnoreCase("true")) {
            txf_id.setText("");
            txf_area.setText("");
            txf_animalNombre.setText("");
            txf_especie.setText("");
            txf_habitad.setText("");
            txf_cuidador.setText("");
            txf_fecha.setText("");
            
            listarDatos();
        }
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        // TODO add your handling code here:
        String id = txf_id.getText();
        String area = txf_area.getText();
        String animal = txf_animalNombre.getText();
        String especie = txf_especie.getText();
        String habitad = txf_habitad.getText();
        String cuidador = txf_cuidador.getText();
        String fecha = txf_fecha.getText();

        List<String> respuesta = actualizar(id, area, animal, especie, habitad, cuidador, fecha);
        JOptionPane.showMessageDialog(null, respuesta.get(0));

        System.out.println(respuesta.get(1));
        if (respuesta.get(1).equalsIgnoreCase("true")) {
            txf_id.setText("");
            txf_area.setText("");
            txf_animalNombre.setText("");
            txf_especie.setText("");
            txf_habitad.setText("");
            txf_cuidador.setText("");
            txf_fecha.setText("");
            
            listarDatos();
        }
    }//GEN-LAST:event_btn_actualizarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        // TODO add your handling code here:
        String id = txf_id.getText();

        List<String> respuesta = eliminar(id);

        System.out.println(respuesta.get(1));
        if (respuesta.get(1).equalsIgnoreCase("true")) {

            JOptionPane.showMessageDialog(null, "Datos encontrados exitosamente.");

            txf_id.setText("");
            txf_area.setText("");
            txf_animalNombre.setText("");
            txf_especie.setText("");
            txf_habitad.setText("");
            txf_cuidador.setText("");
            txf_fecha.setText("");
            
            listarDatos();
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        // TODO add your handling code here:
        String id = txf_id.getText();

        List<String> respuesta = consulta(id);
        JOptionPane.showMessageDialog(null, respuesta.get(7));

        System.out.println(respuesta.get(6));
        if (respuesta.get(6).equalsIgnoreCase("true")) {
            txf_area.setText(respuesta.get(0));
            txf_animalNombre.setText(respuesta.get(1));
            txf_especie.setText(respuesta.get(2));
            txf_habitad.setText(respuesta.get(3));
            txf_cuidador.setText(respuesta.get(4));
            txf_fecha.setText(respuesta.get(5));
        }
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void btn_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listarMouseClicked
        // TODO add your handling code here:
        listarDatos();
    }//GEN-LAST:event_btn_listarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_listar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabla_listar;
    private javax.swing.JTextField txf_animalNombre;
    private javax.swing.JTextField txf_area;
    private javax.swing.JTextField txf_cuidador;
    private javax.swing.JTextField txf_especie;
    private javax.swing.JTextField txf_fecha;
    private javax.swing.JTextField txf_habitad;
    private javax.swing.JTextField txf_id;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<java.lang.String> guardar(java.lang.String id, java.lang.String area, java.lang.String animalNombre, java.lang.String especie, java.lang.String habitad, java.lang.String cuidador, java.lang.String fechaIngreso) {
        zoo_feijoo.ZooWsConexion_Service service = new zoo_feijoo.ZooWsConexion_Service();
        zoo_feijoo.ZooWsConexion port = service.getZooWsConexionPort();
        return port.guardar(id, area, animalNombre, especie, habitad, cuidador, fechaIngreso);
    }

    private static java.util.List<java.lang.String> actualizar(java.lang.String id, java.lang.String area, java.lang.String animalNombre, java.lang.String especie, java.lang.String habitad, java.lang.String cuidador, java.lang.String fechaIngreso) {
        zoo_feijoo.ZooWsConexion_Service service = new zoo_feijoo.ZooWsConexion_Service();
        zoo_feijoo.ZooWsConexion port = service.getZooWsConexionPort();
        return port.actualizar(id, area, animalNombre, especie, habitad, cuidador, fechaIngreso);
    }

    private static java.util.List<java.lang.String> eliminar(java.lang.String id) {
        zoo_feijoo.ZooWsConexion_Service service = new zoo_feijoo.ZooWsConexion_Service();
        zoo_feijoo.ZooWsConexion port = service.getZooWsConexionPort();
        return port.eliminar(id);
    }

    private static java.util.List<java.lang.String> consulta(java.lang.String id) {
        zoo_feijoo.ZooWsConexion_Service service = new zoo_feijoo.ZooWsConexion_Service();
        zoo_feijoo.ZooWsConexion port = service.getZooWsConexionPort();
        return port.consulta(id);
    }

    private static java.util.List<zoo_feijoo.StringArray> listar() {
        zoo_feijoo.ZooWsConexion_Service service = new zoo_feijoo.ZooWsConexion_Service();
        zoo_feijoo.ZooWsConexion port = service.getZooWsConexionPort();
        return port.listar();
    }

    private String[] convertirStringArray(StringArray stringArray) {
        List<String> lista = stringArray.getItem();
        return lista.toArray(new String[0]);
    }
    
    public void listarDatos(){
        try {
            DefaultTableModel tablaModelo = (DefaultTableModel) tabla_listar.getModel();
            tablaModelo.setColumnCount(0);
            tablaModelo.setRowCount(0);

            tablaModelo.addColumn("ID");
            tablaModelo.addColumn("Area");
            tablaModelo.addColumn("Animal");
            tablaModelo.addColumn("Especie");
            tablaModelo.addColumn("Habitad");
            tablaModelo.addColumn("Cuidador");
            tablaModelo.addColumn("Fecha de Ingreso");

            List<StringArray> datosZoo = listar();

            for (StringArray datos : datosZoo) {
                String[] fila = convertirStringArray(datos);
                tablaModelo.addRow(fila);
            }
        } catch (Exception ex) {
            System.out.println("Error al llenar la tabla... " + ex);
        }
    }
}
