/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Fabricio F. Feijoo
 */
public class Vista_Datos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_PacienteCanino
     */
    public Vista_Datos() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_contenedorGeneral = new javax.swing.JPanel();
        jp_contenedor = new javax.swing.JPanel();
        jp_contenedorTitulo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jp_botonSalir = new javax.swing.JPanel();
        lbl_botonSalir = new javax.swing.JLabel();
        jp_contenedorTabla = new javax.swing.JPanel();
        jtb_contenedorDatos = new javax.swing.JScrollPane();
        jtb_tablaDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(904, 715));
        setMinimumSize(new java.awt.Dimension(904, 715));
        setPreferredSize(new java.awt.Dimension(904, 715));

        jp_contenedorGeneral.setMaximumSize(new java.awt.Dimension(904, 694));
        jp_contenedorGeneral.setMinimumSize(new java.awt.Dimension(904, 694));
        jp_contenedorGeneral.setPreferredSize(new java.awt.Dimension(904, 694));

        jp_contenedorTitulo.setPreferredSize(new java.awt.Dimension(754, 80));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Datos de los Usuarios");

        jp_botonSalir.setBackground(new java.awt.Color(204, 204, 204));
        jp_botonSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jp_botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_botonSalir.setMaximumSize(new java.awt.Dimension(130, 36));
        jp_botonSalir.setPreferredSize(new java.awt.Dimension(130, 36));

        lbl_botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_botonSalir.setForeground(new java.awt.Color(0, 0, 0));
        lbl_botonSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/logout_24px.png"))); // NOI18N
        lbl_botonSalir.setText("SALIR");
        lbl_botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_botonSalir.setMaximumSize(new java.awt.Dimension(74, 36));
        lbl_botonSalir.setMinimumSize(new java.awt.Dimension(74, 36));
        lbl_botonSalir.setPreferredSize(new java.awt.Dimension(74, 36));

        javax.swing.GroupLayout jp_botonSalirLayout = new javax.swing.GroupLayout(jp_botonSalir);
        jp_botonSalir.setLayout(jp_botonSalirLayout);
        jp_botonSalirLayout.setHorizontalGroup(
            jp_botonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        jp_botonSalirLayout.setVerticalGroup(
            jp_botonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_contenedorTituloLayout = new javax.swing.GroupLayout(jp_contenedorTitulo);
        jp_contenedorTitulo.setLayout(jp_contenedorTituloLayout);
        jp_contenedorTituloLayout.setHorizontalGroup(
            jp_contenedorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedorTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jp_contenedorTituloLayout.setVerticalGroup(
            jp_contenedorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedorTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jp_contenedorTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        jp_contenedorTabla.setPreferredSize(new java.awt.Dimension(680, 276));

        jtb_contenedorDatos.setMinimumSize(new java.awt.Dimension(882, 250));
        jtb_contenedorDatos.setPreferredSize(new java.awt.Dimension(882, 250));

        jtb_tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtb_contenedorDatos.setViewportView(jtb_tablaDatos);

        javax.swing.GroupLayout jp_contenedorTablaLayout = new javax.swing.GroupLayout(jp_contenedorTabla);
        jp_contenedorTabla.setLayout(jp_contenedorTablaLayout);
        jp_contenedorTablaLayout.setHorizontalGroup(
            jp_contenedorTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb_contenedorDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_contenedorTablaLayout.setVerticalGroup(
            jp_contenedorTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedorTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtb_contenedorDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jp_contenedorLayout = new javax.swing.GroupLayout(jp_contenedor);
        jp_contenedor.setLayout(jp_contenedorLayout);
        jp_contenedorLayout.setHorizontalGroup(
            jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorLayout.createSequentialGroup()
                        .addComponent(jp_contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jp_contenedorTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)))
        );
        jp_contenedorLayout.setVerticalGroup(
            jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_contenedorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_contenedorGeneralLayout = new javax.swing.GroupLayout(jp_contenedorGeneral);
        jp_contenedorGeneral.setLayout(jp_contenedorGeneralLayout);
        jp_contenedorGeneralLayout.setHorizontalGroup(
            jp_contenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jp_contenedorGeneralLayout.setVerticalGroup(
            jp_contenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorGeneralLayout.createSequentialGroup()
                .addComponent(jp_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp_contenedorGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp_contenedorGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jp_botonSalir;
    private javax.swing.JPanel jp_contenedor;
    private javax.swing.JPanel jp_contenedorGeneral;
    private javax.swing.JPanel jp_contenedorTabla;
    private javax.swing.JPanel jp_contenedorTitulo;
    public javax.swing.JScrollPane jtb_contenedorDatos;
    public javax.swing.JTable jtb_tablaDatos;
    private javax.swing.JLabel lbl_botonSalir;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
