/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mongodb_app210623;

import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.MongoException;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.result.UpdateResult;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.bson.Document;
import org.bson.conversions.Bson;

/**
 *
 * @author ANONYMOUS
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txf_codigoCuidador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txf_nombreCuidador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txf_apellido = new javax.swing.JTextField();
        txf_telefonoUno = new javax.swing.JTextField();
        txf_telefonoDos = new javax.swing.JTextField();
        txf_telefonoTres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_buscarCuidador = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_guardarCuidador = new javax.swing.JButton();
        btn_actualizarCuidador = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txf_codigoZona = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txf_descripcionZona = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        btn_guardarZona = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txf_codigoAnimal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txf_especieAnimal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txf_nombreAnimal = new javax.swing.JTextField();
        txf_zonaUno = new javax.swing.JTextField();
        txf_zonaDos = new javax.swing.JTextField();
        txf_zonaTres = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btn_guardarAnimales = new javax.swing.JButton();
        btn_actualizarAnimales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txf_codigoCuidador.setToolTipText("");
        txf_codigoCuidador.setName(""); // NOI18N

        jLabel1.setText("CODIGO:");

        txf_nombreCuidador.setToolTipText("");
        txf_nombreCuidador.setName(""); // NOI18N

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("APELLIDO:");

        jLabel4.setText("TELEFONO 1:");

        jLabel5.setText("TELEFONO 2:");

        jLabel6.setText("TELEFONO 3:");

        btn_buscarCuidador.setText("BUSCAR");
        btn_buscarCuidador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarCuidadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txf_codigoCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txf_nombreCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txf_telefonoTres, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txf_telefonoDos)
                            .addComponent(txf_apellido)
                            .addComponent(txf_telefonoUno))))
                .addGap(35, 35, 35)
                .addComponent(btn_buscarCuidador)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txf_codigoCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarCuidador))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_nombreCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txf_telefonoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_telefonoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_telefonoTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btn_guardarCuidador.setText("GUARDAR");
        btn_guardarCuidador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarCuidadorMouseClicked(evt);
            }
        });

        btn_actualizarCuidador.setText("ACTUALIZAR");
        btn_actualizarCuidador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarCuidadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btn_guardarCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_actualizarCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizarCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuidador", jPanel1);

        txf_codigoZona.setToolTipText("");
        txf_codigoZona.setName(""); // NOI18N

        jLabel7.setText("CODIGO:");

        jLabel8.setText("DESCRIPCION:");

        txf_descripcionZona.setColumns(20);
        txf_descripcionZona.setRows(5);
        jScrollPane1.setViewportView(txf_descripcionZona);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txf_codigoZona))
                .addGap(113, 113, 113))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txf_codigoZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btn_guardarZona.setText("GUARDAR");
        btn_guardarZona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarZonaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(btn_guardarZona, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btn_guardarZona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Zona", jPanel2);

        txf_codigoAnimal.setToolTipText("");
        txf_codigoAnimal.setName(""); // NOI18N

        jLabel13.setText("CODIGO:");

        txf_especieAnimal.setToolTipText("");
        txf_especieAnimal.setName(""); // NOI18N

        jLabel14.setText("ESPECIE:");

        jLabel15.setText("NOMBRE:");

        jLabel16.setText("ZONA 1:");

        jLabel17.setText("ZONA 2:");

        jLabel18.setText("ZONA 3:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txf_codigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txf_especieAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txf_zonaTres)
                            .addComponent(txf_zonaDos)
                            .addComponent(txf_nombreAnimal)
                            .addComponent(txf_zonaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(138, 138, 138))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txf_codigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_especieAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txf_nombreAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txf_zonaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_zonaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_zonaTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btn_guardarAnimales.setText("GUARDAR");
        btn_guardarAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarAnimalesMouseClicked(evt);
            }
        });

        btn_actualizarAnimales.setText("ACTUALIZAR");
        btn_actualizarAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarAnimalesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btn_guardarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_actualizarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Animales", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarCuidadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarCuidadorMouseClicked
        // TODO add your handling code here:

        String codigo = txf_codigoCuidador.getText();
        String nombre = txf_nombreCuidador.getText();
        String apellido = txf_apellido.getText();
        String telefonoUno = txf_telefonoUno.getText();
        String telefonoDos = txf_telefonoDos.getText();
        String telefonoTres = txf_telefonoTres.getText();

        boolean validar = false;

        // Crear una lista para almacenar los teléfonos
        List<String> telefonos = new ArrayList<>();

        // Agregar los teléfonos a la lista si tienen valores
        if (!telefonoUno.isEmpty()) {
            telefonos.add(telefonoUno);
        }
        if (!telefonoDos.isEmpty()) {
            telefonos.add(telefonoDos);
        }
        if (!telefonoTres.isEmpty()) {
            telefonos.add(telefonoTres);
        }

        Conexion conexion = new Conexion();
        MongoClient mongoClient = conexion.getMongoClient();

        // Obtener una base de datos
        MongoDatabase database = mongoClient.getDatabase("baseDatosZoo");

        // Obtener una colección
        MongoCollection<Document> collection = database.getCollection("cuidador");

        // Crear un documento
        Document documento = new Document("codigo", codigo)
                .append("nombre", nombre)
                .append("apellido", apellido)
                .append("telefono", telefonos);

        // Insertar el documento en la colección
        collection.insertOne(documento);

        // Validar si el documento se guardó correctamente
        Object id = documento.get("_id");
        if (id != null) {
            System.out.println("Documento guardado correctamente en MongoDB");
            JOptionPane.showMessageDialog(null, "Documento guardado correctamente en MongoDB");
            validar = true;
        } else {
            System.out.println("Error al guardar el documento en MongoDB");
            JOptionPane.showMessageDialog(null, "Error al guardar el documento en MongoDB");
        }

        // Cerrar la conexión cuando ya no se necesite
        conexion.cerrarConexion();

        if (validar) {
            txf_codigoCuidador.setText("");
            txf_nombreCuidador.setText("");
            txf_apellido.setText("");
            txf_telefonoUno.setText("");
            txf_telefonoDos.setText("");
            txf_telefonoTres.setText("");
        }
    }//GEN-LAST:event_btn_guardarCuidadorMouseClicked

    private void btn_guardarZonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarZonaMouseClicked
        // TODO add your handling code here:

        String codigo = txf_codigoZona.getText();
        String descripcion = txf_descripcionZona.getText();

        Conexion conexion = new Conexion();
        MongoClient mongoClient = conexion.getMongoClient();

        // Obtener una base de datos
        MongoDatabase database = mongoClient.getDatabase("baseDatosZoo");

        // Obtener una colección
        MongoCollection<Document> collection = database.getCollection("zona");

        // Crear un documento
        Document documento = new Document("codigo", codigo)
                .append("descripcion", descripcion);

        // Insertar el documento en la colección
        collection.insertOne(documento);

        // Validar si el documento se guardó correctamente
        Object id = documento.get("_id");
        if (id != null) {
            System.out.println("Documento guardado correctamente en MongoDB");
            JOptionPane.showMessageDialog(null, "Documento guardado correctamente en MongoDB");
        } else {
            System.out.println("Error al guardar el documento en MongoDB");
            JOptionPane.showMessageDialog(null, "Error al guardar el documento en MongoDB");
        }

        // Cerrar la conexión cuando ya no se necesite
        conexion.cerrarConexion();
    }//GEN-LAST:event_btn_guardarZonaMouseClicked

    private void btn_guardarAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarAnimalesMouseClicked
        // TODO add your handling code here:

        String codigo = txf_codigoAnimal.getText();
        String especie = txf_especieAnimal.getText();
        String nombre = txf_nombreAnimal.getText();
        String zonaUno = txf_zonaUno.getText();
        String zonaDos = txf_zonaDos.getText();
        String zonaTres = txf_zonaTres.getText();

        // Crear una lista para almacenar los teléfonos
        List<String> zonas = new ArrayList<>();

        // Agregar los teléfonos a la lista si tienen valores
        if (!zonaUno.isEmpty()) {
            zonas.add(zonaUno);
        }
        if (!zonaDos.isEmpty()) {
            zonas.add(zonaDos);
        }
        if (!zonaTres.isEmpty()) {
            zonas.add(zonaTres);
        }

        Conexion conexion = new Conexion();
        MongoClient mongoClient = conexion.getMongoClient();

        // Obtener una base de datos
        MongoDatabase database = mongoClient.getDatabase("baseDatosZoo");

        // Obtener una colección
        MongoCollection<Document> collection = database.getCollection("zona");

        // Crear un documento
        Document documento = new Document("codigo", codigo)
                .append("especie", especie)
                .append("nombre", nombre)
                .append("zona", zonas);

        // Insertar el documento en la colección
        collection.insertOne(documento);

        // Validar si el documento se guardó correctamente
        Object id = documento.get("_id");
        if (id != null) {
            System.out.println("Documento guardado correctamente en MongoDB");
            JOptionPane.showMessageDialog(null, "Documento guardado correctamente en MongoDB");
        } else {
            System.out.println("Error al guardar el documento en MongoDB");
            JOptionPane.showMessageDialog(null, "Error al guardar el documento en MongoDB");
        }

        // Cerrar la conexión cuando ya no se necesite
        conexion.cerrarConexion();
    }//GEN-LAST:event_btn_guardarAnimalesMouseClicked

    private void btn_actualizarAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarAnimalesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_actualizarAnimalesMouseClicked

    private void btn_actualizarCuidadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarCuidadorMouseClicked
        // TODO add your handling code here:
        String codigo = txf_codigoCuidador.getText();
        String nombre = txf_nombreCuidador.getText();
        String apellido = txf_apellido.getText();
        String telefonoUno = txf_telefonoUno.getText();
        String telefonoDos = txf_telefonoDos.getText();
        String telefonoTres = txf_telefonoTres.getText();

        boolean validar = false;

        // Crear una lista para almacenar los teléfonos
        List<String> telefonos = new ArrayList<>();

        // Agregar los teléfonos a la lista si tienen valores
        if (!telefonoUno.isEmpty()) {
            telefonos.add(telefonoUno);
        }
        if (!telefonoDos.isEmpty()) {
            telefonos.add(telefonoDos);
        }
        if (!telefonoTres.isEmpty()) {
            telefonos.add(telefonoTres);
        }

        Conexion conexion = new Conexion();
        MongoClient mongoClient = conexion.getMongoClient();

        // Obtener una base de datos
        MongoDatabase database = mongoClient.getDatabase("baseDatosZoo");

        // Obtener una colección
        MongoCollection<Document> collection = database.getCollection("cuidador");

        // Crear un filtro para buscar el documento a actualizar
        Bson filtro = Filters.eq("codigo", codigo);

        // Crear un documento con los nuevos valores
        Document nuevoDocumento = new Document("$set", new Document("nombre", nombre)
                .append("apellido", apellido)
                .append("telefono", telefonos));

        // Actualizar el documento en la colección
        UpdateResult result = collection.updateOne(filtro, nuevoDocumento);

        // Validar si el documento se actualizó correctamente
        if (result.getModifiedCount() > 0) {
            System.out.println("Documento actualizado correctamente en MongoDB");
            JOptionPane.showMessageDialog(null, "Documento actualizado correctamente en MongoDB");
            validar = true;
        } else {
            System.out.println("Error al actualizar el documento en MongoDB");
            JOptionPane.showMessageDialog(null, "Error al actualizar el documento en MongoDB");
        }

        // Cerrar la conexión cuando ya no se necesite
        conexion.cerrarConexion();

        if (validar) {
            txf_codigoCuidador.setText("");
            txf_nombreCuidador.setText("");
            txf_apellido.setText("");
            txf_telefonoUno.setText("");
            txf_telefonoDos.setText("");
            txf_telefonoTres.setText("");
        }
    }//GEN-LAST:event_btn_actualizarCuidadorMouseClicked

    private void btn_buscarCuidadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarCuidadorMouseClicked
        // TODO add your handling code here:
        String codigo = txf_codigoCuidador.getText();

        Conexion conexion = new Conexion();
        MongoClient mongoClient = conexion.getMongoClient();

        // Obtener una base de datos
        MongoDatabase database = mongoClient.getDatabase("baseDatosZoo");

        // Obtener una colección
        MongoCollection<Document> collection = database.getCollection("cuidador");

        // Crear un filtro para buscar documentos que coincidan con el código del cuidador
        Document filtro = new Document("codigo", codigo);

        // Realizar la búsqueda y obtener el primer documento encontrado
        Document documentoEncontrado = collection.find(filtro).first();

        // Validar si se encontró un documento
        if (documentoEncontrado != null) {
            // Obtener los valores de los campos del documento
            String codigoEncontrado = documentoEncontrado.getString("codigo");
            String nombreEncontrado = documentoEncontrado.getString("nombre");
            String apellidoEncontrado = documentoEncontrado.getString("apellido");
            List<String> telefonosEncontrados = documentoEncontrado.getList("telefono", String.class);

            // Cargar los valores en los campos de texto de la interfaz
            txf_codigoCuidador.setText(codigoEncontrado);
            txf_nombreCuidador.setText(nombreEncontrado);
            txf_apellido.setText(apellidoEncontrado);
            txf_telefonoUno.setText(telefonosEncontrados.get(0));
            if (telefonosEncontrados.size() > 1) {
                txf_telefonoDos.setText(telefonosEncontrados.get(1));
            } else {
                txf_telefonoDos.setText("");
            }
            if (telefonosEncontrados.size() > 2) {
                txf_telefonoTres.setText(telefonosEncontrados.get(2));
            } else {
                txf_telefonoTres.setText("");
            }

            System.out.println("Documento encontrado en MongoDB");
        } else {
            System.out.println("No se encontró el documento en MongoDB");
        }

        // Cerrar la conexión cuando ya no se necesite
        conexion.cerrarConexion();
    }//GEN-LAST:event_btn_buscarCuidadorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarAnimales;
    private javax.swing.JButton btn_actualizarCuidador;
    private javax.swing.JButton btn_buscarCuidador;
    private javax.swing.JButton btn_guardarAnimales;
    private javax.swing.JButton btn_guardarCuidador;
    private javax.swing.JButton btn_guardarZona;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txf_apellido;
    private javax.swing.JTextField txf_codigoAnimal;
    private javax.swing.JTextField txf_codigoCuidador;
    private javax.swing.JTextField txf_codigoZona;
    private javax.swing.JTextArea txf_descripcionZona;
    private javax.swing.JTextField txf_especieAnimal;
    private javax.swing.JTextField txf_nombreAnimal;
    private javax.swing.JTextField txf_nombreCuidador;
    private javax.swing.JTextField txf_telefonoDos;
    private javax.swing.JTextField txf_telefonoTres;
    private javax.swing.JTextField txf_telefonoUno;
    private javax.swing.JTextField txf_zonaDos;
    private javax.swing.JTextField txf_zonaTres;
    private javax.swing.JTextField txf_zonaUno;
    // End of variables declaration//GEN-END:variables

    public class Conexion {

        private MongoClient mongoClient;

        public Conexion() {
            try {
                // Cadena de conexión a MongoDB
                String connectionString = "mongodb://localhost:27017";

                // Crear el objeto MongoClientURI con la cadena de conexión
                MongoClientURI uri = new MongoClientURI(connectionString);

                // Crear una instancia de MongoClient utilizando el MongoClientURI
                mongoClient = new MongoClient(uri);

                // Imprimir mensaje de éxito si la conexión es exitosa
                System.out.println("Conexión exitosa a MongoDB");
            } catch (MongoException e) {
                // Imprimir mensaje de error en caso de excepción
                System.err.println("Error al conectar a MongoDB: " + e.getMessage());
            }
        }

        public MongoClient getMongoClient() {
            return mongoClient;
        }

        public void cerrarConexion() {
            if (mongoClient != null) {
                mongoClient.close();
                System.out.println("Conexión cerrada con éxito");
            }
        }
    }
}
